### ISSUE TITLE
Need enemies

### ISSUE THREAD

**Issue by ciaranmul** [ciaranmul/gameJam2017#3]
Enemy needs to be added

-  enemy should be spooky and have wave-like features
-  could be an eel or snake with wave-like movement
-  enemy should chase player when it sees them

**Comment by ciaran036** [comment]
Started working on enemy spawn.

**Comment by ciaran036** [comment]
Completed enemy spawn. Working on enemy behaviour

**Comment by ciaranmul** [comment]
Enemy behaviour completed
